CC = g++
LIB = -lSDL2 -lSDL2_image -lsdl2_mixer -lSDL2_ttf

game.o: src/main.cpp
	$(CC) src/main.cpp $(LIB) -o game
		#-framework SDL2 -I/Library/Frameworks/SDL2.framework/Headers/ \
			#-I/Library/Frameworks/SDL2_image.framework/Headers/ \
			#-I/Library/Frameworks/SDL2_ttf.framework/Headers/
