game.o: src/main.cpp
	g++ src/main.cpp -lSDL2 -lSDL2_image -lSDL2_ttf
		#-framework SDL2 -I/Library/Frameworks/SDL2.framework/Headers/ \
			#-I/Library/Frameworks/SDL2_image.framework/Headers/ \
			#-I/Library/Frameworks/SDL2_ttf.framework/Headers/
